### ISSUE TITLE
https://developers.redhat.com/products/openjdk/download/?sc_cid=701f2000000RWTnAAO

### ISSUE THREAD

**Issue by keenomvictor** [microsoft/vscode-azure-account#898]
@keenomvictor #896 
<details><summary>Details</summary>
<p>

</p>
</details>  @[

Does this occur consistently? 
Repro steps:

1.
2.

Version: 0.11.6
OS: win32
OS Release: 10.0.22635
Product: Visual Studio Code
Product Version: 1.84.2
Language: en
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-azure-account/issues/896
- [ ] https://github.com/microsoft/vscode-azure-account/issues/894
- [ ] https://github.com/microsoft/vscode-azure-account/issues/886
- [ ] https://github.com/microsoft/vscode-azure-account/issues/886
```

**Comment by nturinski** [comment]
Are you a bot? 🤖

**Comment by keenomvictor** [comment]
> Are you a bot? 🤖

Is that your problem ?

**Comment by keenomvictor** [comment]
> Are you a bot? 🤖 you have the chance of making it right but no you want to make fun of your self
