### ISSUE TITLE
dh-az-orko

### ISSUE THREAD

**Issue by dh-orko** [microsoft/vscode-azure-account#903]
Does this occur consistently? 
Repro steps:

1.
2.

Version: 0.11.6
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.84.2
Language: en
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-azure-account/issues/902
- [ ] https://github.com/microsoft/vscode-azure-account/issues/891
- [ ] https://github.com/microsoft/vscode-azure-account/issues/892
- [ ] https://github.com/microsoft/vscode-azure-account/issues/898
- [ ] https://github.com/microsoft/vscode-azure-account/issues/901
- [ ] https://github.com/microsoft/vscode-azure-account/issues/896
- [ ] https://github.com/microsoft/vscode-azure-account/issues/900
- [ ] https://github.com/microsoft/vscode-azure-account/issues/899
- [ ] https://github.com/microsoft/vscode-azure-account/issues/295
- [ ] https://github.com/microsoft/vscode-azure-account/issues/887
- [ ] https://github.com/microsoft/vscode-azure-account/issues/897
- [ ] https://github.com/microsoft/vscode-azure-account/issues/894
- [ ] https://github.com/microsoft/vscode-azure-account/issues/886
- [ ] https://github.com/microsoft/vscode-azure-account/issues/885
- [ ] https://github.com/microsoft/vscode-azure-account/issues/895
- [ ] https://github.com/microsoft/vscode-azure-account/pull/889
- [ ] https://github.com/microsoft/vscode-azure-account/issues/890
- [ ] https://github.com/microsoft/vscode-azure-account/issues/877
- [ ] https://github.com/microsoft/vscode-azure-account/issues/881
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-azure-account/issues/902
- [ ] https://github.com/microsoft/vscode-azure-account/issues/891
- [ ] https://github.com/microsoft/vscode-azure-account/issues/901
- [ ] https://github.com/microsoft/vscode-azure-account/issues/898
- [ ] https://github.com/microsoft/vscode-azure-account/issues/892
- [ ] https://github.com/microsoft/vscode-azure-account/issues/900
- [ ] https://github.com/microsoft/vscode-azure-account/issues/295
- [ ] https://github.com/microsoft/vscode-azure-account/issues/897
- [ ] https://github.com/microsoft/vscode-azure-account/issues/894
```
