### ISSUE TITLE
System Gold NOTKOIN-NOT

### ISSUE THREAD

**Issue by SystemGold777** [microsoft/vscode-azure-account#952]
The issue text was copied to the clipboard.  Please paste it into this window.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-azure-account/issues/947
- [ ] https://github.com/microsoft/vscode-azure-account/issues/949
- [ ] https://github.com/microsoft/vscode-azure-account/pull/950
- [ ] https://github.com/microsoft/vscode-azure-account/issues/951
- [ ] https://github.com/microsoft/vscode-azure-account/issues/897
- [ ] https://github.com/microsoft/vscode-azure-account/issues/948
- [ ] https://github.com/microsoft/vscode-azure-account/issues/945
- [ ] https://github.com/microsoft/vscode-azure-account/issues/733
- [ ] https://github.com/microsoft/vscode-azure-account/issues/901
- [ ] https://github.com/microsoft/vscode-azure-account/issues/938
- [ ] https://github.com/microsoft/vscode-azure-account/issues/941
- [ ] https://github.com/microsoft/vscode-azure-account/pull/943
- [ ] https://github.com/microsoft/vscode-azure-account/pull/936
- [ ] https://github.com/microsoft/vscode-azure-account/issues/935
```
