### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by zlatur** [microsoft/vscode-azure-account#970]
- VS Code Version:
- Azure Account Extension Version:
- OS Version:

Are you connected to a proxy server? Yes/No

Steps to Reproduce:

1.yes
![Сборка ДВОЙНАЯ](https://github.com/microsoft/vscode-azure-account/assets/32998661/25156bf8-fe65-4a92-8182-f2329522193d)

2.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-azure-account/issues/951
- [ ] https://github.com/microsoft/vscode-azure-account/issues/956
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-azure-account/issues/978
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-azure-account/issues/946
```
